### PR TITLE
RAAW Controller

### PR DESCRIPTION
**Pull request by ptrbortolotti**
## Description and Purpose
I'm tuning ROSCO for the GE turbine used in RAAW and I had to come up with a couple fixes:
- Larger pitch TSR ranges to handle high cut out
- Fix bug for non monothonic Cp

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

### CODE REVIEW

**Comment by ptrbortolotti** [comment]
Tests won't pass because of pyparsing 3.0, we should downgrade to 2.3.1

**Comment by nikhar-abbas** [comment]
@ptrbortolotti, thanks for this! It looks like it was running with pyparsing=2.4.7 in previous tests ([here](https://github.com/NREL/ROSCO/runs/3909379277?check_suite_focus=true#step:7:23))

Do you mind adding the updated dependency to the environment.yml file? And pushing?
**https://github.com/NREL/ROSCO/blob/develop/environment.yml**

**Comment by nikhar-abbas** [comment]
Okay, it looks like the pyparsing problem is solved. There's a small bug with the conda-forge distribution of OpenFAST that is being fixed as we speak - I think all the tests should pass once that bug is fixed!

**Comment by dzalkind** [comment]
Thanks, @ptrbortolotti! I'm going to do some merging and push to this branch.  Hopefully, that will restart the CI and it all passes :-)

**Pull request merged**
