### PR TITLE
Update ReadWrite_FAST.m

### PR DESCRIPTION
**Pull request by void1981**
## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

TODO Items General:
- [ ] Add example/test for new feature
- [ ] Update registry
- [ ] Run testing

TODO Items API Change:
- [ ] Update docs with API change
- [ ] Run update_rosco_discons.py in Test_Cases/
- [ ] Update DISCON schema

### CODE REVIEW

**Comment by void1981** [comment]
It runs correctly so.

**Comment by dzalkind** [comment]
I am guessing you used an absolute path for the CpCtCq file path in the DISCON?  I try to have these examples work for users without extra setup and using relative paths.  Typically ROSCO looks for the CpCtCq file relative to the DISCON file path, which is in the regular (non-Simulink) NREL-5MW Test_Case.  The change I made should do that.  Does it work for you?

**Comment by void1981** [comment]
This also does not work. I got these errors.
```
Error using Pre_LoadRotPerf
Error loading file

Error in ReadWrite_FAST (line 48)
Cx                      = Pre_LoadRotPerf(fullfile(discon_dir,PerfFileName(2:end-1)));

Error in runFAST (line 29)
[Param,Cx] = ReadWrite_FAST(fast);
```
As I understand, you have already defined the path for the CpCtCq file in these lines

```
[~,SD_dllFile]          = GetFASTPar_Subfile(SvDP,'DLL_InFile',fast.FAST_directory, fast.FAST_directory);
SD_dllP                 = ROSCO2Matlab(SD_dllFile,2);
PerfFileName            = GetFASTPar(SD_dllP,'PerfFileName');
```
The last one `PerfFileName` which you used to call already has the full path.

When combined `discon_dir` or `fast.FAST_directory` with `PerfFileName`, got that error.

**Comment by void1981** [comment]
Okay, I figured it out, you were right, that error because in DISCON.IN file, I have an absolute path to the CpCtCq file.

**Comment by dzalkind** [comment]
I'd like to re-open this and merge it in because this also drives me crazy when I use the matlab interface.  I would have thought that absolute paths would overrule the relative ones in fullfile().  At least that's how the python version works :-). I'll check on it and push a fix that works with absolute paths, too.

**Pull request closed without merging**
