### PR TITLE
Modified ZeroMQ interface to include pitch offsets

### PR DESCRIPTION
**Pull request by mvanv**
## Description and Purpose
I've updated the zmq interface to now also allow individual pitch setpoints. I've created an example '24_zeromq_pitch.py' to showcase the new feature, which is a slightly modified version of '17_zeromq_interface.py'. 

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

TODO Items General:
- [ ] Add example/test for new feature
- [ ] Update registry
- [ ] Run testing

TODO Items API Change:
- [ ] Update docs with API change
- [ ] Run update_rosco_discons.py in Test_Cases/
- [ ] Update DISCON schema

## Examples/Testing, if applicable
24_zeromq_pitch.py

### CODE REVIEW

**Comment by dzalkind** [comment]
Thanks for the update, @mvanv.  To clarify, it looks like you want to add _offsets_ to the pitch command via the zeromq interface?  Rather than directly overwriting the pitch signal.

If you're willing to share, what is your goal for using this type of control/interface?

Do you mind if I make some edits to the PR and perhaps combine the pitch example with the yaw example?  I'd also like to add a check to see that the information is passed properly, for both pitch and yaw.

Over the next year, we are planning on developing the zeromq interface further for passing information to ROSCO during simulations, so we may change some of the details of this implementation, but we'll try to maintain this PR's functionality.

**Comment by mvanv** [comment]
Hi @dzalkind,

That's right. The feature is intended for IPC-type controllers, whose pitch commands are superimposed on the collective pitch. One could for example communicate pitch commands from a data-driven IPC which requires a solver, or use a wake mixing controller which requires an estimator, which is my goal with this interface.

I agree it makes sense to merge the examples. For simplicity, I decided to communicate a pitch offset, which might cause confusion about the purpose. If you'd like to have something more complex to clarify the purpose of the feature better, it might be more appropriate to communicate a sine wave representing dynamic induction control.

Great to hear you are planning on developing zeromq further. I also noticed there is a problem with the update time of zeromq, which cannot be smaller than approximately 0.5s. This is relevant for communicating dynamic pitch signals as they will be quite coarse for large update steps. I found this problem is due to a conditional statement with floating point numbers. I'm working on a solution for that as well.

**Comment by dzalkind** [comment]
Interesting, thanks for the information!

I wasn't aware of the update time limit. Can you point me to that?  A shorter update period would enable more active external controllers.

**Comment by mvanv** [comment]
I've added the fix in a new commit, let me know if you agree.

**Comment by dzalkind** [comment]
Hi @mvanv,

I've made a few changes to your PR here to keep things consistent with te rest of the repo, but I've tried to maintain the functionality of your original feature.  Can you confirm that the new, combined example (`17_zeromq_interface.py`) is demonstrating the feature you intended to add?

Thanks!

Best, Dan

**Pull request merged**
