### PR TITLE
Shubham baisthakur patch 1

### PR DESCRIPTION
**Pull request by shubham-baisthakur**
## Description and Purpose
The ROSCO source code is converted to MATLAB, and the function and variable definitions are modified accordingly to suit the MATLAB coding environment
## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

### CODE REVIEW

**Comment by shubham-baisthakur** [comment]
Hello there,
I have never used the GitHub forum before, so pardon me if I haven't followed the right approach to contribute to the repository.

The main aim of this pull request is to contribute the Matlab implementation of ROSCO source code to the repository. I have developed an indigenous model of the 15MW wind turbine using Kane's Dynamics approach in Matlab. I wanted to benchmark this model against the OpenFast and hence converted the ROSCO source code to Matlab to have a consistent control behaviour. I am able to match the Opefast response pretty well. There is still a slight difference in the generator torque estimated in Openfast and in my model. I am sharing the ROSCO source code I am using; if you could review it, it would be a great help.

I hope this will also help other researchers who prefer to work in Matlab.

Cheers,
Shubham

**Comment by dzalkind** [comment]
Hi Shubham,

Very cool! Unfortunately, I'm not sure we can add this to the official NREL repository. We've recently spent a lot of time ensuring that updates to the ROSCO software are well tested and documented in official releases that can be referenced. Since we at NREL are a research institution and not a software company, our code must be easy to maintain.  If this Matlab implementation were incorporated into our repository, the community would surely use this valuable tool, and that would come with the expectation that we answer questions and ensure that it works properly. We would need to ensure that your Matlab version of ROSCO matches our Fortran version 100% and works for all the test cases we currently support.  Additionally, each bug that we fix in Fortran would need to be implemented in Matlab. We could add a disclaimer that your Matlab version is a learning tool (like we do for the Simulink), but I've already seen the community use that and disregard the releases we carefully maintain.  In the end, this would essentially double the amount of software engineering that we would need to do for any ROSCO changes, and we don't have the resources to support that at this time.

I'm sorry for this long response, but I wanted to provide you with adequate justification in line with the large amount of work you did.

I'd like to propose an alternative that could satisfy your needs and help us maintain a single version of ROSCO.  There are ways to load and call dynamic libraries in Matlab/Simulink.  The OpenFAST team does this and I would like to reproduce their work so that Matlab users can use official versions of our controller.  I would be happy to work on this to ensure it satisfies your research objectives and gives us all a way to use ROSCO in a Matlab environment while satisfying all of our maintenance needs.

Best, Dan

**Comment by shubham-baisthakur** [comment]
Thanks for your comment, Dan. I completely understand your perspective. I would very much appreciate if you could share the link where I can find out how to load and call ROSCO dll in Matlab. That way, I can compare the results from the Matlab and the official ROSCO versions. It would work as a benchmarking exercise.

Thanks,
Shubham

**Comment by dzalkind** [comment]
Hi Shubham,

I haven't started on this yet, but here are a few places I was planning on starting:

https://www.mathworks.com/help/matlab/ref/loadlibrary.html
https://github.com/OpenFAST/openfast/tree/main/glue-codes/simulink/src

I will keep you posted and if you learn anything in the meantime, please let us know.

Best, Dan

**Comment by hugocastroo** [comment]
Hello @shubham-baisthakur did you get further on this topic?

I am trying to load the libdiscon.dll in Matlab but had no success yet, for now, I could use other different dll controllers, but I am struggling with the ROSCO dll, the saddest part is that Matlab is just crashing and is not giving me an error, so I don't really have a start point. Here is some of my code:


%Here is my code
DllFile                 = '..\MM92_OpenFAST\Rediscon\libdiscon.dll'; %dll file path
InFile                	= '..\MM92_OpenFAST\Rediscon\DISCONMM92.IN'; %in file path

% load lib
[DllFolder,LibraryName,~]   = fileparts(DllFile);
if libisloaded(LibraryName)
    unloadlibrary(LibraryName); 
end

HeaderFile          = fullfile(DllFolder,[LibraryName,'.h']); % header file for using the loadlibrary function

[notfound, warnings] = loadlibrary(DllFile, HeaderFile); %Load library function, tried with more arguments but did not work see below
%[notfound, warnings] = loadlibrary(DllFile, HeaderFile, 'mfilename', %%'mHeader'); %tried this using something found in a MATLAB forum but did %%not work https://de.mathworks.com/matlabcentral/answers/96578-why-does-matlab-crash-when-i-make-a-function-call-on-a-dll-in-matlab-7-6-r2008a
%[notfound, warnings] = loadlibrary('library.dll',@mHeader); %did not work

calllib(LibraryName,'DISCON',avrSwap,0,accInfile,avcOutname,avcMsg); %After loading the library, I call the library

When using the code with other dlls it works fine, I already tried it with 3 different dlls, and just with the ROSCO dll is Matlab crashing, anyway when loading exactly the same dll with OpenFAST it works.

I tried it in different Matlabs (2022a and 2015b) with 64 and 32 bit compilled rosco controllers, but it ain't working either 32 nor 64 bits.

You can check a bit more of the code in the files attached, I stored them as txt Datei to be able to upload them.


[libdiscon.txt](https://github.com/NREL/ROSCO/files/10807611/libdiscon.txt)
[MatlabLoadLL.txt](https://github.com/NREL/ROSCO/files/10807619/MatlabLoadLL.txt)

**Comment by shubham-baisthakur** [comment]
Hello @hugocastroo,
I actually started my work trying to use the similar approach and I was facing the similar issues. I was not able to identify the exact reason behind it and so I coded the ROSCO source code in Matlab.
I plan to get back to this to validate the Matlab code using the dll file from ROSCO but at the moment I am working on another project and will probably take this up at the later stage. At this moment I won't be able to offer you much help.
Good luck with your analysis and please post on the forum if you get this working.

Regards,
Shubham

**Pull request closed without merging**
