### PR TITLE
Update CMakeLsits for VS and ifort compilation

### PR DESCRIPTION
**Pull request by ghylander**
## Description and Purpose
Updated CMakeLists now differentiates between GNU and Intel compilers when in WIN32 platform.

The develop branch seems to be a bit outdated (and I modified the CMakeLists file starting from the oneROSCO2 branch), so there seems to be some minor changes. You can probably cherry pick the changes later when merging the changes to the main branch

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Github issues addressed, if one exists
#66

### CODE REVIEW

**Comment by nikhar-abbas** [comment]
@ghylander you will need to pull in the most recent NREL/develop branch and resolve the merge conflicts before we can accept this pull request.

**Comment by rafmudaf** [comment]
@ghylander I've git-rebased your develop branch onto the latest in NREL/ROSCO. See [here](https://github.com/rafmudaf/ROSCO/tree/ghylander_rebase). If this looks correct to you, you can either create a new pull request from my branch or you can download my branch and push to your fork. Let me know if you want to talk through that process.

Alternatively, you can do the rebase yourself on your existing develop branch. Also, let me know if you want to talk through that.

**Comment by rafmudaf** [comment]
BTW the reason I did a rebase is because there were over 600 files different between ghylander/develop and NREL/develop. After merging, it was difficult to see whether things were correctly merged.

**Comment by ghylander** [comment]
That's quite confusing, I simply created a local branch from the develop branch and then overwrote the CMakeLists.txt file
That file is the only difference that shows up for me
Even in the "files changed" tab of the PR

**Comment by ghylander** [comment]
Well I think I fixed it, should be ok now

**Comment by rafmudaf** [comment]
@ghylander Yea, I don't know what I was looking at initially. Your merge commit looks good. Thanks for updating that.

**Comment by dzalkind** [comment]
Thanks all!

**Pull request merged**
